<?php

namespace Sonder\Exceptions;

use Exception;

class AppException extends Exception
{
    const CODE_CORE_MODEL_NOT_EXISTS = 1001;
    const CODE_CORE_PLUGIN_NOT_EXISTS = 1002;

    const CODE_ENDPOINT_RESPONSE_IS_EMPTY = 2001;
    const CODE_ENDPOINT_CONTROLLER_IS_NOT_SET = 2002;
    const CODE_ENDPOINT_INVALID_CONTROLLER_METHOD = 2003;

    const CODE_MIDDLEWARE_CONTROLLER_IS_NOT_SET = 3001;
    const CODE_MIDDLEWARE_METHOD_IS_NOT_SET = 3002;
    const CODE_MIDDLEWARE_CSRF_RUNNING_BEFORE_SESSION = 3003;
    const CODE_MIDDLEWARE_USER_RUNNING_BEFORE_SESSION = 3004;
    const CODE_MIDDLEWARE_ROUTING_TYPE_IS_NOT_SUPPORTED = 3005;

    const CODE_HOOK_VALUE_NOT_EXISTS = 4001;

    const CODE_API_URL_HAS_BAD_FORMAT = 5001;
    const CODE_API_CAN_NOT_RETRIEVE_MODEL = 5003;
    const CODE_API_NOT_SUPPORTED_API_CALLS = 5004;
    const CODE_API_INVALID_CRUD_ACTION = 5005;
    const CODE_API_INVALID_HTTP_METHOD = 5006;
}
