<?php
/**
 * @var int $code
 * @var string $message
 * @var string $file
 * @var int $line
 */

?>
<div class="error_wrapper">
    <div>
        Error #<?= $code; ?> <strong><?= $message; ?></strong>
    </div>
    <div>
        File: <strong><?= $file; ?></strong> (<?= $line; ?>)
    </div>
    <div>
        <strong>Trace:</strong>
        <?php
        if (!empty($debugBacktrace)):
            foreach ($debugBacktrace as $debugBacktraceStep):
                ?>
                <div>
                    <?= $debugBacktraceStep; ?>
                </div>
            <?php
            endforeach;
        endif;
        ?>
    </div>
</div>
<style>
    div {
        font-size: 18px;
        font-family: Arial, sans-serif;
        line-height: 1.5rem;
        padding: .125rem;
        margin: .125rem;
    }

    .error_wrapper {
        color: #FEFEFE;
        background: #C00;
        padding: .5rem;
        margin: .5rem;
        border: 1px solid #333;
        border-radius: .125rem;
    }
</style>
