<form action="#" method="GET">
    <p>
        <input type="text"
               name="text"
               placeholder="Lorem ipsum dolor sit amet"
               value="Lorem ipsum dolor sit amet">
    </p>
    <p>
        <input type="file" name="file">
    </p>
    <p>
        <select name="select">
            <option value="default" selected disabled>Default</option>
            <option value="foo">Foo</option>
            <option value="bar">Bar</option>
            <option value="test">Test</option>
        </select>
    </p>
    <p>
        <input type="checkbox"
               name="check">
        <label>Lorem ipsum dolor sit amet</label>
    </p>
    <p>
        <input type="password"
               name="password"
               value="Lorem ipsum dolor sit amet">
    </p>
    <p>
        <textarea name="textarea" placeholder="Lorem ipsum dolor sit amet">
<?php __part('lorem_ipsum'); ?>
        </textarea>
    </p>
    <p>
        <input type="radio"
               name="radio"
               value="default"
               checked>
        <label>Default</label>
    </p>
    <p>
        <input type="radio" name="radio" value="foo"><label>Foo</label>
    </p>
    <p>
        <input type="radio" name="radio" value="bar"><label>Bar</label>
    </p>
    <p>
        <input type="radio" name="radio" value="test"><label>Test</label>
    </p>
    <p>
        <input type="submit" value="Send">
    </p>
</form>
