<!DOCTYPE html>
<html>
<head>
    <title><?=$meta['title'];?></title>
    <meta charset="utf-8" />
    <?php
        __part('meta');
        __part('css');
    ?>
</head>
<body>
<div class="header">
    <?php if ($currentUrl != '/'): ?>
        <a href="/" class="site-title"><?=$meta['site_name'];?></a>
    <?php else: ?>
        <h1 class="site-title"><?=$meta['site_name'];?></h1>
    <?php endif; ?>
    <div class="site-subtitle"><?=$meta['site_slogan'];?></div>
    <div class="main-menu">
        <a href="/">Main</a>
        <a href="/page/example/">Example</a>
        <a href="/error/404/">Error 404</a>
    </div>
</div>
<div class="clear"></div>
<div class="content">
    <?php if ($currentUrl != '/'): ?>
        <?=$breadcrumbs;?>
        <div class="clear"></div>
    <?php endif; ?>
