<h1>Header 1</h1>
<h2>Header 2</h2>
<h3>Header 3</h3>
<h4>Header 4</h4>
<h5>Header 5</h5>
<h6>Header 6</h6>
<p>
    <strong>Bold</strong>
    <i>Italic</i>
    <strike>Stike</strike>
    <span class="u">Underline</span>
    <a href="#">Link</a>
    <?php __part('lorem_ipsum'); ?>
</p>
<p>
    <?php __part('lorem_ipsum'); ?>
</p>
<p>
    <?php __part('lorem_ipsum'); ?></p>
<p>
<ul>
    <li>One</li>
    <li>Two</li>
    <li>Three</li>
</ul>
</p>
<p>
<ol>
    <li>One</li>
    <li>Two</li>
    <li>Three</li>
</ol>
</p>
<p>
    <?php __part('lorem_ipsum'); ?></p>
<p>
    <img src="/assets/img/broken.png">
</p>
<p>
    <?php __part('lorem_ipsum'); ?>
</p>
<p>
<blockquote><?php __part('lorem_ipsum'); ?></blockquote>
<div class="clear"></div>
</p>
<p>
    <?php __part('lorem_ipsum'); ?>
</p>
<p>
    <?php __part('form'); ?>
</p>
<p>
    <?php __part('lorem_ipsum'); ?>
</p>
