<?php

namespace Sonder\Plugins\Image\Exceptions;

class ImageException extends \Exception
{
    const CODE_PLUGIN_FILE_NAME_IS_NOT_SET = 1001;
    const CODE_PLUGIN_FILE_PATH_IS_NOT_SET = 1002;
    const CODE_PLUGIN_DIR_PATH_IS_NOT_SET = 1003;
    const CODE_PLUGIN_FILE_PREFIX_IS_EMPTY = 1004;
    const CODE_PLUGIN_SIZE_OBJECT_IS_EMPTY = 1005;
    const CODE_PLUGIN_VALUES_HAS_BAD_FORMAT = 1006;
    const CODE_PLUGIN_ORIGINAL_HEIGHT_IS_EMPTY = 1007;
    const CODE_PLUGIN_ORIGINAL_WIDTH_IS_EMPTY = 1008;
    const CODE_PLUGIN_IMAGE_OBJECT_IS_EMPTY = 1009;
    const CODE_PLUGIN_FILE_ALREADY_EXISTS = 1010;

    const CODE_SIZE_VALUES_NOT_SET = 2001;
    const CODE_SIZE_VALUES_HAS_BAD_FORMAT = 2002;
    const CODE_SIZE_HEIGHT_VALUE_IS_EMPTY = 2003;
    const CODE_SIZE_WIDTH_VALUE_IS_EMPTY = 2004;
    const CODE_SIZE_FULL_PREFIX_NOT_ALLOWED = 2005;
}
