<div    style="
            background:#C00;
            font-size:16px;
            font-family:Arial,sans-serif;
            color:#FEFEFE;
            border:1px solid #333;
            border-radius:.125em;
            padding:.5em;
            margin:.5em;
            line-height:1.5em;">
    Error #<?=$code;?> <strong><?=$message;?></strong>
    <br>
    File: <strong><?=$file;?></strong> (<?=$line;?>)
    <br>
    <strong>Trace:</strong>
    <br>
    <?php
    if (!empty($debugBacktrace)):
        foreach ($debugBacktrace as $debugBacktraceStep):
    ?>
    <?=$debugBacktraceStep;?>
    <br>
    <?php
        endforeach;
    endif;
    ?>
</div>
